/*
SQLyog Ultimate - MySQL GUI v8.22 
MySQL - 5.1.66-0+squeeze1 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/link/fotball/link','{\"islive\":\"\",\"linktext\":\"TITLE\",\"lastchecked\":\"\",\"description\":\"DESCRIPTION\",\"linksource\":\"SOURCE\",\"url\":\"URL\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/media/fotball/media','{\"author\":\"\",\"binary\":\"BINARY\",\"location\":\"HEADLINE\",\"description\":\"INTRO\",\"name\":\"NAME\",\"copyright\":\"\",\"alttext\":\"\",\"local-caption\":\"\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/multimedia/fotball/multimedia','{\"HTML\":\"HTML\",\"VIEW\":\"VIEW\",\"TITLE\":\"TITLE\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/news/fotball/blog','{\"FPNUMRELATEDARTICLES\":\"\",\"EMBED-CODE-FOR-LIVE\":\"\",\"MAILTO_HA\":\"\",\"MAILTO_BTR\":\"\",\"FRONTPAGETITLE\":\"\",\"LINKTEXT\":\"LINKTEXT\",\"FPALTERNATETITLEDISPLAY\":\"\",\"MAILTO_BT\":\"\",\"SHOWRELATEDLEAGUES\":\"\",\"SHOWRELATEDTEAMS\":\"\",\"MAILTO_RB\":\"\",\"ALLOWDEBATE\":\"\",\"BREAKINGNEWS\":\"\",\"FRONTPAGEPOLLDISPLAY\":\"\",\"LEAGUECATEGORY\":\"RELATEDLEAGUES_ADRLEGACY\",\"TEAMCATEGORY\":\"RELATEDTEAMS_ADRLEGACY\",\"BODYFULLWIDTH\":\"\",\"WAPTITLE\":\"\",\"MAILTO_AA\":\"\",\"FASTSEARCHKEYWORDS\":\"RELATEDPLAYERS_ADRLEGACY\",\"FRONTPAGELEADTEXT\":\"\",\"RUNNINGHEAD\":\"RUNNINGHEAD\",\"POLLID\":\"\",\"MAILTO_FVN\":\"\",\"MAILTO_SMP\":\"\",\"FRONTPAGERUNNINGHEAD\":\"\",\"FASTSEARCHTIMESTAMP\":\"\",\"LEADTEXT\":\"LEADTEXT\",\"MAILTO_SA\":\"\",\"MAILTO_AP\":\"\",\"SHOWRELATEDPLAYERS\":\"\",\"BODY\":\"BODYTEXT\",\"BYLINE\":\"BYLINE\",\"WAPLEADTEXT\":\"\",\"FPIMAGEDISPLAYTYPE\":\"\",\"WAPBODY\":\"\",\"TITLE\":\"TITLE\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/news/fotball/editorial','{\"FPNUMRELATEDARTICLES\":\"\",\"EMBED-CODE-FOR-LIVE\":\"\",\"MAILTO_HA\":\"\",\"MAILTO_BTR\":\"\",\"FRONTPAGETITLE\":\"\",\"LINKTEXT\":\"LINKTEXT\",\"FPALTERNATETITLEDISPLAY\":\"\",\"MAILTO_BT\":\"\",\"SHOWRELATEDLEAGUES\":\"\",\"SHOWRELATEDTEAMS\":\"\",\"MAILTO_RB\":\"\",\"ALLOWDEBATE\":\"\",\"BREAKINGNEWS\":\"\",\"FRONTPAGEPOLLDISPLAY\":\"\",\"LEAGUECATEGORY\":\"RELATEDLEAGUES_ADRLEGACY\",\"TEAMCATEGORY\":\"RELATEDTEAMS_ADRLEGACY\",\"BODYFULLWIDTH\":\"\",\"WAPTITLE\":\"\",\"MAILTO_AA\":\"\",\"FASTSEARCHKEYWORDS\":\"RELATEDPLAYERS_ADRLEGACY\",\"FRONTPAGELEADTEXT\":\"\",\"RUNNINGHEAD\":\"RUNNINGHEAD\",\"POLLID\":\"\",\"MAILTO_FVN\":\"\",\"MAILTO_SMP\":\"\",\"FRONTPAGERUNNINGHEAD\":\"\",\"FASTSEARCHTIMESTAMP\":\"\",\"LEADTEXT\":\"LEADTEXT\",\"MAILTO_SA\":\"\",\"MAILTO_AP\":\"\",\"SHOWRELATEDPLAYERS\":\"\",\"BODY\":\"BODYTEXT\",\"BYLINE\":\"BYLINE\",\"WAPLEADTEXT\":\"\",\"FPIMAGEDISPLAYTYPE\":\"\",\"WAPBODY\":\"\",\"TITLE\":\"TITLE\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/news/fotball/fxtvArticle','{\"FPNUMRELATEDARTICLES\":\"\",\"EMBED-CODE-FOR-LIVE\":\"\",\"MAILTO_HA\":\"\",\"MAILTO_BTR\":\"\",\"FRONTPAGETITLE\":\"\",\"LINKTEXT\":\"LINKTEXT\",\"FPALTERNATETITLEDISPLAY\":\"\",\"MAILTO_BT\":\"\",\"SHOWRELATEDLEAGUES\":\"\",\"SHOWRELATEDTEAMS\":\"\",\"MAILTO_RB\":\"\",\"ALLOWDEBATE\":\"\",\"BREAKINGNEWS\":\"\",\"FRONTPAGEPOLLDISPLAY\":\"\",\"LEAGUECATEGORY\":\"RELATEDLEAGUES_ADRLEGACY\",\"TEAMCATEGORY\":\"RELATEDTEAMS_ADRLEGACY\",\"BODYFULLWIDTH\":\"\",\"WAPTITLE\":\"\",\"MAILTO_AA\":\"\",\"FRONTPAGELEADTEXT\":\"\",\"RUNNINGHEAD\":\"RUNNINGHEAD\",\"POLLID\":\"\",\"MAILTO_FVN\":\"\",\"MAILTO_SMP\":\"\",\"FRONTPAGERUNNINGHEAD\":\"\",\"MAILTO_SA\":\"\",\"LEADTEXT\":\"LEADTEXT\",\"MAILTO_AP\":\"\",\"SHOWRELATEDPLAYERS\":\"\",\"BODY\":\"BODYTEXT\",\"BYLINE\":\"BYLINE\",\"WAPLEADTEXT\":\"\",\"FPIMAGEDISPLAYTYPE\":\"\",\"WAPBODY\":\"\",\"TITLE\":\"TITLE\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/news/fotball/imageSeriesArticle','{\"FPNUMRELATEDARTICLES\":\"\",\"EMBED-CODE-FOR-LIVE\":\"\",\"MAILTO_HA\":\"\",\"MAILTO_BTR\":\"\",\"FRONTPAGETITLE\":\"\",\"LINKTEXT\":\"LINKTEXT\",\"FPALTERNATETITLEDISPLAY\":\"\",\"MAILTO_BT\":\"\",\"SHOWRELATEDLEAGUES\":\"\",\"SHOWRELATEDTEAMS\":\"\",\"MAILTO_RB\":\"\",\"ALLOWDEBATE\":\"\",\"BREAKINGNEWS\":\"\",\"FRONTPAGEPOLLDISPLAY\":\"\",\"LEAGUECATEGORY\":\"RELATEDLEAGUES_ADRLEGACY\",\"TEAMCATEGORY\":\"RELATEDTEAMS_ADRLEGACY\",\"BODYFULLWIDTH\":\"\",\"WAPTITLE\":\"\",\"MAILTO_AA\":\"\",\"FRONTPAGELEADTEXT\":\"\",\"RUNNINGHEAD\":\"RUNNINGHEAD\",\"POLLID\":\"\",\"MAILTO_FVN\":\"\",\"MAILTO_SMP\":\"\",\"FRONTPAGERUNNINGHEAD\":\"\",\"MAILTO_SA\":\"\",\"LEADTEXT\":\"LEADTEXT\",\"MAILTO_AP\":\"\",\"SHOWRELATEDPLAYERS\":\"\",\"BODY\":\"BODYTEXT\",\"BYLINE\":\"BYLINE\",\"WAPLEADTEXT\":\"\",\"FPIMAGEDISPLAYTYPE\":\"\",\"WAPBODY\":\"\",\"TITLE\":\"TITLE\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/news/fotball/sportArticle','{\"FPNUMRELATEDARTICLES\":\"\",\"EMBED-CODE-FOR-LIVE\":\"\",\"MAILTO_HA\":\"\",\"MAILTO_BTR\":\"\",\"FRONTPAGETITLE\":\"\",\"LINKTEXT\":\"LINKTEXT\",\"FPALTERNATETITLEDISPLAY\":\"\",\"SPORTSHOWRELATEDSPORTS\":\"\",\"MAILTO_BT\":\"\",\"MAILTO_RB\":\"\",\"SPORTTEAMCATEGORY\":\"RELATEDSPORTSTAGS_ADRLEGACY\",\"ALLOWDEBATE\":\"\",\"BREAKINGNEWS\":\"\",\"FRONTPAGEPOLLDISPLAY\":\"\",\"BODYFULLWIDTH\":\"\",\"WAPTITLE\":\"\",\"MAILTO_AA\":\"\",\"FRONTPAGELEADTEXT\":\"\",\"RUNNINGHEAD\":\"RUNNINGHEAD\",\"POLLID\":\"\",\"MAILTO_FVN\":\"\",\"MAILTO_SMP\":\"\",\"SPORTSCATEGORY\":\"RELATEDSPORTS_ADRLEGACY\",\"FRONTPAGERUNNINGHEAD\":\"\",\"MAILTO_SA\":\"\",\"LEADTEXT\":\"LEADTEXT\",\"MAILTO_AP\":\"\",\"BODY\":\"BODYTEXT\",\"SPORTSHOWRELATEDTEAMS\":\"\",\"BYLINE\":\"BYLINE\",\"WAPLEADTEXT\":\"\",\"FPIMAGEDISPLAYTYPE\":\"\",\"WAPBODY\":\"\",\"TITLE\":\"TITLE\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/news/fotball/standardArticle','{\"FPNUMRELATEDARTICLES\":\"\",\"EMBED-CODE-FOR-LIVE\":\"\",\"MAILTO_HA\":\"\",\"MAILTO_BTR\":\"\",\"FRONTPAGETITLE\":\"\",\"LINKTEXT\":\"LINKTEXT\",\"FPALTERNATETITLEDISPLAY\":\"\",\"MAILTO_BT\":\"\",\"SHOWRELATEDLEAGUES\":\"\",\"SHOWRELATEDTEAMS\":\"\",\"MAILTO_RB\":\"\",\"ALLOWDEBATE\":\"\",\"BREAKINGNEWS\":\"\",\"FRONTPAGEPOLLDISPLAY\":\"\",\"LEAGUECATEGORY\":\"RELATEDLEAGUES_ADRLEGACY\",\"TEAMCATEGORY\":\"RELATEDTEAMS_ADRLEGACY\",\"BODYFULLWIDTH\":\"\",\"WAPTITLE\":\"\",\"MAILTO_AA\":\"\",\"FASTSEARCHKEYWORDS\":\"RELATEDPLAYERS_ADRLEGACY\",\"FRONTPAGELEADTEXT\":\"\",\"RUNNINGHEAD\":\"RUNNINGHEAD\",\"POLLID\":\"\",\"MAILTO_FVN\":\"\",\"MAILTO_SMP\":\"\",\"FRONTPAGERUNNINGHEAD\":\"\",\"FASTSEARCHTIMESTAMP\":\"\",\"LEADTEXT\":\"LEADTEXT\",\"MAILTO_SA\":\"\",\"MAILTO_AP\":\"\",\"SHOWRELATEDPLAYERS\":\"\",\"BODY\":\"BODYTEXT\",\"BYLINE\":\"BYLINE\",\"WAPLEADTEXT\":\"\",\"FPIMAGEDISPLAYTYPE\":\"\",\"WAPBODY\":\"\",\"TITLE\":\"TITLE\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/picture/fotball/image','{\"binary\":\"BINARY\",\"location\":\"CAPTION\",\"description\":\"DESCRIPTION\",\"name\":\"\",\"photographer\":\"PHOTOGRAPHER\",\"copyright\":\"\",\"alttext\":\"ALTTEXT\",\"local-caption\":\"\"}');
insert into `PublicationResource` (`referenceID`, `uri`, `data`) values('1','publication:/migration-tool/mapping/content-type/video/fotball/xstreamVideoArticle','{\"FPNUMRELATEDARTICLES\":\"\",\"UPDATEDBY\":\"\",\"MAILTO_HA\":\"\",\"MAILTO_BTR\":\"\",\"FRONTPAGETITLE\":\"\",\"STATUS\":\"\",\"FPALTERNATETITLEDISPLAY\":\"\",\"MAILTO_BT\":\"\",\"SHOWRELATEDLEAGUES\":\"\",\"SHOWRELATEDTEAMS\":\"\",\"CREATEDBY\":\"CREATEDBY_ADRLEGACY\",\"VIDEOCATEGORIES\":\"\",\"MAILTO_RB\":\"\",\"THUMBNAILURL\":\"THUMBNAILURL_ADRLEGACY\",\"VIDEORATING\":\"\",\"BREAKINGNEWS\":\"\",\"LEAGUECATEGORY\":\"RELATEDLEAGUES_ADRLEGACY\",\"TEAMCATEGORY\":\"RELATEDTEAMS_ADRLEGACY\",\"VIDEOTAGS\":\"\",\"DURATION\":\"DURATION_ADRLEGACY\",\"MAILTO_AA\":\"\",\"FRONTPAGELEADTEXT\":\"\",\"VIDEOURL\":\"VIDEOURL_ADRLEGACY\",\"RUNNINGHEAD\":\"RUNNINGHEAD\",\"CREATEDDATE\":\"CREATEDDATE_ADRLEGACY\",\"MAILTO_FVN\":\"\",\"MAILTO_SMP\":\"\",\"FRONTPAGERUNNINGHEAD\":\"\",\"MAILTO_SA\":\"\",\"LEADTEXT\":\"LEADTEXT\",\"MAILTO_AP\":\"\",\"MEDIAID\":\"MEDIAID_ADRLEGACY\",\"SHOWRELATEDPLAYERS\":\"\",\"ACTIVATIONDATE\":\"\",\"FORMAT\":\"\",\"VIDEOHITS\":\"\",\"LASTEDITEDDATE\":\"\",\"FPIMAGEDISPLAYTYPE\":\"\",\"TITLE\":\"TITLE\"}');
